In [1]:

import tensorflow as tf
import keras

from keras.datasets import  fashion_mnist

Using TensorFlow backend.


In [35]:
from keras.utils import np_utils

from keras.models import Sequential
from keras.layers import Dense, Activation



In [36]:
(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

In [37]:
import numpy as np

In [38]:
np.shape(x_train)

(60000, 28, 28)

In [39]:
x_train=x_train.reshape(60000,784).astype('float32')/255.0

In [40]:
np.shape(x_train)

(60000, 784)

In [41]:
x_test=x_test.reshape(10000,784).astype('float32')/255.0


In [42]:
y_train=np_utils.to_categorical(y_train)

In [43]:
y_train

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [44]:
y_test

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [45]:
y_test=np_utils.to_categorical(y_test)

In [46]:
y_test

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [47]:
model=Sequential()
model.add(Dense(units=64, input_dim =28*28, activation='relu'))
model.add(Dense(units=10, activation='softmax'))


In [48]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])




In [50]:
hist=model.fit(x_train,y_train,epochs=100, batch_size=32)

Epoch 1/100
60000/60000 [==============================] - 3s 46us/step - loss: 0.4298 - acc: 0.8515
Epoch 2/100
60000/60000 [==============================] - 3s 44us/step - loss: 0.4187 - acc: 0.8551
Epoch 3/100
60000/60000 [==============================] - 3s 44us/step - loss: 0.4109 - acc: 0.8574
Epoch 4/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.4022 - acc: 0.8610
Epoch 5/100
60000/60000 [==============================] - 3s 46us/step - loss: 0.3957 - acc: 0.8627
Epoch 6/100
60000/60000 [==============================] - 3s 46us/step - loss: 0.3884 - acc: 0.8649
Epoch 7/100
60000/60000 [==============================] - 3s 46us/step - loss: 0.3836 - acc: 0.8657
Epoch 8/100
60000/60000 [==============================] - 3s 47us/step - loss: 0.3786 - acc: 0.8688
Epoch 9/100
60000/60000 [==============================] - 3s 48us/step - loss: 0.3721 - acc: 0.8699
Epoch 10/100
60000/60000 [==============================] - 3s 49us/step - loss: 0.3670 - a

60000/60000 [==============================] - 3s 43us/step - loss: 0.2258 - acc: 0.9202
Epoch 82/100
60000/60000 [==============================] - 3s 43us/step - loss: 0.2248 - acc: 0.9205
Epoch 83/100
60000/60000 [==============================] - 3s 43us/step - loss: 0.2238 - acc: 0.9202
Epoch 84/100
60000/60000 [==============================] - 3s 43us/step - loss: 0.2224 - acc: 0.9211
Epoch 85/100
60000/60000 [==============================] - 3s 43us/step - loss: 0.2221 - acc: 0.9207
Epoch 86/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.2207 - acc: 0.9221
Epoch 87/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.2194 - acc: 0.9223
Epoch 88/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.2184 - acc: 0.9228
Epoch 89/100
60000/60000 [==============================] - 3s 44us/step - loss: 0.2180 - acc: 0.9218
Epoch 90/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.2169 - acc: 

In [51]:
print("loss and acc")
print("loss is ", hist.history['loss'])
print("accuracy is ", hist.history['acc'])

loss and acc
loss is  [0.42980259201129278, 0.41871880141496659, 0.41086124784151712, 0.40219193610747656, 0.39568770991563795, 0.38843902092377347, 0.3836236974477768, 0.37859060720205306, 0.37207452571392058, 0.36697953250010806, 0.36270901318788529, 0.35735516702731451, 0.35341678082545597, 0.34909500222603479, 0.3457787355621656, 0.34135487498839695, 0.33813007644812265, 0.33483577595949171, 0.33171296456654864, 0.32723387274742127, 0.32442066851456958, 0.32109562359650928, 0.31846993805567425, 0.31562622044285138, 0.31258783653974531, 0.31062578079104425, 0.30769662676652271, 0.30496479412714639, 0.30260658916036287, 0.29989846034447354, 0.29790099476178489, 0.29566761836012206, 0.29324130902091661, 0.29100616056919099, 0.28874651771187781, 0.28732355446616809, 0.28560042048295337, 0.28287447969913482, 0.28139464713533718, 0.27999406715333464, 0.27732398022810617, 0.27610794130961103, 0.27406283447345098, 0.27276485618352891, 0.26995722473661105, 0.26881076306502022, 0.26751801065

In [52]:
loss_and_metrics = model.evaluate(x_test,y_test,batch_size=32)

print("##evaluation loss and met##")
print(loss_and_metrics)

10000/10000 [==============================] - 0s 22us/step
##evaluation loss and met##
[0.35923916482925417, 0.87929999999999997]
